### ISSUE TITLE
[Bug] Daily Check-in Notification always popup after couple of hour

### ISSUE THREAD

**Issue by GhifariYusuf10** [URK96/ResinTimer#39]

**Comment by URK96** [comment]
@GhifariYusuf10 Thanks to report bug.

What game type of Daily Check-in notification did you enabled and popup issue? (Genshin or Honkai or StarRail)

**Comment by GhifariYusuf10** [comment]
After checking, my genshin auto daily login didn't work, and for star rails i keep getting an error message "Failed to checkin

**Comment by URK96** [comment]
Okay, thank you for description.

I will check this bug and fix as soon as possible

**Comment by GhifariYusuf10** [comment]
Thanks, let me know if u want to ask for more detail

**Comment by Moravuscz** [comment]
@URK96 This is most likely caused by miHoYo introducing a captcha on the daily login, at least on Genshin. When I click Claim the app gives me a toast that claim was successful, but it actually isn't. When I then visit the web version in-app and click the item to claim I'm presented with a captcha (find and click 3 shapes in an image in the correct order, can post screenshot later).

Not sure what's wrong for HSR, but it's broken as well.

**Comment by URK96** [comment]
@Moravuscz @GhifariYusuf10 
Yes, i already check that captcha system is added on Genshin Daily Reward page.

Also, miHoYo change Genshin Daily Reward API and result data. (Maybe they will apply this format on Honkai & Honkai StarRail)

So i working now to chage API implement and apply on newer version.

**Comment by URK96** [comment]
@Moravuscz @GhifariYusuf10 
This issue is fixed on v1.21.2

Please check new version. Thanks to report issue   x~x

**Comment by GhifariYusuf10** [comment]
Thank youu so much for fixing this issue, i'll wait until the newer version appear on the play store

**Comment by GhifariYusuf10** [comment]
Looks like the check-in is finally working perfectly fine.. thanks for fixing this bug
